[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "LLM from scratch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.2",
    "tiktoken>=0.8.0",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
]
